version: '3.1'
services:
  spring-boot-dev:
    build: .
    # working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      # - .:/app
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./frontend:/app/frontend
    # command: mvn spring-boot:run
    command: tail -f /dev/null
    # command: /app/mvnw clean spring-boot:run
  mysqldb:
    image: mysql:8.0.31
    # build:
    #   context: ./mysql
    #   dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: capit_ai_root_password
      MYSQL_DATABASE: capit_ai
      MYSQL_USER: capit_ai_dba
      MYSQL_PASSWORD: capit_ai_dba_password
    # volumes:
    #   - mysql:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysqldb

# volumes:
#   mysql:
