version: '3.1'
services:
  spring-boot-dev:
    build:
      context: .
      secrets:
        - mysql_ca_cert
    # working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      # - .:/app
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./secrets:/app/secrets
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/capit-ai-firebase-adminsdk.json
      FIREBASE_DATABASE: https://capitai-default-rtdb.firebaseio.com
      DATASOURCE_URL: jdbc:mysql://mysqldb:3306/capit_ai?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      DATASOURCE_USERNAME: capit_ai_dba
      DATASOURCE_PASSWORD: capit_ai_dba_password
      SPRING_PROFILES_ACTIVE: dev
    # secrets:
    #   - mysql_ca_cert
    # command: mvn spring-boot:run
    command: tail -f /dev/null
    # command: /app/mvnw clean spring-boot:run
  mysqldb:
    image: mysql:8.0.31
    # build:
    #   context: ./mysql
    #   dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: capit_ai_root_password
      MYSQL_DATABASE: capit_ai
      MYSQL_USER: capit_ai_dba
      MYSQL_PASSWORD: capit_ai_dba_password
    # volumes:
    #   - mysql:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysqldb

# volumes:
#   mysql:

secrets:
  mysql_ca_cert:
    file: ./secrets/ca-certificate.crt
